### ISSUE TITLE
Image uses depreciated mbed Enabled logo

### ISSUE THREAD

**Issue by sg-** [ARMmbed/target-frdm-k64f-gcc#14]
Please change to use the image here. http://www.mbed.com/en/development/hardware/boards/freescale/frdm_k64f/

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-885

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1003

**Comment by autopulated** [comment]
(this was resolved by #16)
