### ISSUE TITLE
PwmOut on K64F does not work

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/target-frdm-k64f-gcc#23]
In the other issue ppl said because it was D8, which was causing the problems, but it's not. D3 works fine in classic, doesn't work in mbed OS.

mbed Classic (works):

```cpp
#include "mbed.h"
PwmOut led(D3);
 
int main() {
    while(1) {
        for(float p = 0.0f; p < 1.0f; p += 0.1f) {
            led = p;
            wait(0.1);
        }
    }
}
```

mbed OS, doesnt work:

```cpp
static PwmOut led(D3);
float a = 0.0f;
static void blinky(void) {
    a += 0.1f;
    if (a > 1.0f) a = 0.0f;
    
    led = a;
}

void app_start(int, char**) {
    get_stdio_serial().baud(115200);
    minar::Scheduler::postCallback(blinky).period(minar::milliseconds(100));
}
```

This is kind of a real problem for me, as a bunch of things I need to demo on Monday require PWM...

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2126

**Comment by 0xc0170** [comment]
Duplicate of https://github.com/ARMmbed/mbed-drivers/issues/158. I am closing this one.
