### ISSUE TITLE
Unused K64FN1M0xxx12.ld file

### ISSUE THREAD

**Issue by meriac** [ARMmbed/target-frdm-k64f-gcc#24]
Hi @autopulated,

I've stumbled over the unused K64FN1M0xxx12.ld linker script (which i tried to edit without actually changing thing :-). Can we please remove it so others won't make the same mistake?

I've read your comment at https://github.com/ARMmbed/target-frdm-k64f-gcc/commit/c6e2926c3034301d83bda32a67cb336a876a0000 which explains the reasoning behind keeping it? Is it really necessary to keep that file?

@bogdanm

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2336

**Comment by autopulated** [comment]
Yup leaving it was an intermediate thing, should be fine to remove it now.

**Comment by meriac** [comment]
@autopulated removed linker script.
