### ISSUE TITLE
target .ld file seems not to be used for anything?

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/target-frdm-k64f-gcc#26]
I have noticed that the frdm-k64f-gcc .ld file is never used with yotta, instead the inherited kinetics-k64f-gcc is used.

After building a test-application I can see these contents:

kinetis-64f-gcc

MEMORY
{
  VECTORS (rx)          : ORIGIN = 0x00000000, LENGTH = 0x00000400
  FLASH_PROTECTION (rx) : ORIGIN = 0x00000400, LENGTH = 0x00000010
  FLASH (rx)            : ORIGIN = 0x00000410, LENGTH = 0x00100000 - 0x00000410
  RAM_RESERVED (rwx)    : ORIGIN = 0x1FFF0000, LENGTH = 0x00000200
  RAM (rwx)             : ORIGIN = 0x1FFF0200, LENGTH = 0x00010000 - 0x00000200
  RAM2 (rwx)            : ORIGIN = 0x20000000, LENGTH = 0x00030000 
}

frdm-k64f-gcc (which appears after yotta update)
MEMORY
{
  VECTORS (rx)          : ORIGIN = 0x00000000, LENGTH = 0x00000400
  FLASH_PROTECTION (rx) : ORIGIN = 0x00000400, LENGTH = 0x00000010
  FLASH (rx)            : ORIGIN = 0x00000410, LENGTH = 0x00100000 - 0x00000410
  RAM (rwx)             : ORIGIN = 0x1FFF0200, LENGTH = 0x00040000 - 0x00000200
}

Even making changes to frdm-k64f-gcc is not registered. I would expect that the frdm-k64f-gcc .ld file would be identical and changes to it would override the kinetis .ld file.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2514
